/*!
 * SAP UI development toolkit for HTML5 (SAPUI5/OpenUI5)
 * (c) Copyright 2009-2014 SAP AG or an SAP affiliate company. 
 * Licensed under the Apache License, Version 2.0 - see LICENSE.txt.
 */
jQuery.sap.declare("sap.ui.commons.MessageBar");jQuery.sap.require("sap.ui.commons.library");jQuery.sap.require("sap.ui.core.Control");sap.ui.core.Control.extend("sap.ui.commons.MessageBar",{metadata:{deprecated:true,publicMethods:["addMessages","deleteMessages","deleteAllMessages"],library:"sap.ui.commons",properties:{"anchorID":{type:"string",group:"Appearance",defaultValue:''},"visible":{type:"boolean",group:"Behavior",defaultValue:true},"maxToasted":{type:"int",group:"Misc",defaultValue:3},"maxListed":{type:"int",group:"Misc",defaultValue:7},"anchorSnapPoint":{type:"string",group:"Misc",defaultValue:"begin top"}}}});jQuery.sap.require("sap.ui.core.Popup");
sap.ui.commons.MessageBar.prototype.init=function(){this.aErrors=[];this.aWarnings=[];this.aSuccesses=[];this.aToasts=[];this.maxToastsReached=false;this.oPopup=new sap.ui.core.Popup(this,false,true,false);this.oList=null;var i=this.getId();this.oToast=new sap.ui.commons.MessageToast(i+"__Toast",{anchorId:i+"__sums"});var t=this;this.oToast.attachNext(function(){t.checkForToast()});this.snapPoint=null;this.oHomePosition=null;this.oDropPosition=null;this.bToggleListBackAfterDrag=null};
sap.ui.commons.MessageBar.prototype.exit=function(){this.onmouseup();this.close();this.oPopup.destroy();this.oPopup=null;this.oToast.destroy();this.oToast=null;if(this.oList){this.oList.destroy();this.oList=null}};
sap.ui.commons.MessageBar.prototype.ondragstart=function(e){e.preventDefault();e.stopPropagation()};
sap.ui.commons.MessageBar.prototype.onmousedown=function(e){var s=e.target;var S=jQuery(s);if(S.css('cursor')!="move"){return}this.sDragMode="move";this.oMsgBarDragStartPosition=this.$().rect();this.oMsgBarDragStartPosition.right=Number(this.$().css('right').replace("px",""));if(!this.oHomePosition){this.oHomePosition=this.oMsgBarDragStartPosition}this.mouseDragStartPositionX=e.screenX;this.mouseDragStartPositionY=e.screenY;var d=jQuery(window.document);d.bind("mousemove",jQuery.proxy(this.handleMove,this));if(window.parent){jQuery(window.parent.document).bind("mousemove",jQuery.proxy(this.handleMove,this),true)}d.bind("selectstart",jQuery.proxy(this.ondragstart,this),true)};
sap.ui.commons.MessageBar.prototype.handleMove=function(e){if(!this.sDragMode){return}if(this.bToggleListBackAfterDrag==null&&this.oList){this.bToggleListBackAfterDrag=this.oList.getVisible();if(this.bToggleListBackAfterDrag){this.toggleList()}}e=e||window.event;var t=this.oMsgBarDragStartPosition.top+e.screenY-this.mouseDragStartPositionY;var l=this.oMsgBarDragStartPosition.left+e.screenX-this.mouseDragStartPositionX;var r=this.oMsgBarDragStartPosition.right-e.screenX+this.mouseDragStartPositionX;this.oPopup._$().css('top',t);if(this.snapPoint.indexOf("right")!=-1){this.oPopup._$().css('right',r)}else{this.oPopup._$().css('left',l)}this.oDropPosition={top:t,left:l,right:r};e.cancelBubble=true;return false};
sap.ui.commons.MessageBar.prototype.onmouseup=function(e){if(!this.sDragMode){return}if(this.oDropPosition){this.addStyleClass("sapUiMsgBarMoved")}if(this.bToggleListBackAfterDrag){this.toggleList()}this.bToggleListBackAfterDrag=null;var d=jQuery(window.document);d.unbind("mousemove",jQuery.proxy(this.handleMove,this));if(window.parent){jQuery(window.parent.document).unbind("mousemove",jQuery.proxy(this.handleMove,this))}d.unbind("selectstart",jQuery.proxy(this.ondragstart,this));this.sDragMode=null;this.checkForToast()};
sap.ui.commons.MessageBar.prototype.onclick=function(e){var s=e.target;var S=jQuery(s);if(S.css('cursor')!="pointer"){return}if(S.hasClass("sapUiMsgBarToggle")){this.toggleList()}else if(S.hasClass("sapUiMsgBarHome")){this.backHome()}else{jQuery.sap.log.debug("Warning: MessageBar unsupported click on "+S.attr('className'))}};
sap.ui.commons.MessageBar.prototype.checkForToast=function(){if(this.maxToastsReached){return}if(this.aToasts==null||this.aToasts.length==0){return}var m=this.getMaxToasted();if(m==0){return}if(this.sDragMode){return}var n=null;var a="";if(this.aToasts.length>this.getMaxToasted()){this.aToasts=[];this.maxToastsReached=true;a=this.getId()+"__arrowImg"}else{if(!this.oToast.isIdle()){return}n=this.aToasts.splice(0,1)[0];a=this.getId()+"__"+n.getType()+"Img"}this.oToast.toast(n,a)};
sap.ui.commons.MessageBar.prototype.addToasts=function(m){for(var i=0,l=m.length;i<l;i++){var n=m[i];var a=false;for(var j=this.aToasts.length;j>=0;j--){if(n==this.aToasts[j]){a=true;break}}if(!a){this.aToasts.push(n)}}};
sap.ui.commons.MessageBar.prototype.deleteToast=function(i){if(!this.aToasts){return}for(var j=0,l=this.aToasts.length;j<l;j++){if(this.aToasts[j].getId()==i){this.aToasts.splice(j,1);return}}};
sap.ui.commons.MessageBar.prototype.deleteOneMessage=function(i){if(!i){return}for(var j=0,l=this.aErrors.length;j<l;j++){if(this.aErrors[j].getId()==i){this.aErrors[j].closeDetails();this.aErrors.splice(j,1);return}}for(var j=0,l=this.aWarnings.length;j<l;j++){if(this.aWarnings[j].getId()==i){this.aWarnings[j].closeDetails();this.aWarnings.splice(j,1);return}}for(var j=0,l=this.aSuccesses.length;j<l;j++){if(this.aSuccesses[j].getId()==i){this.aSuccesses[j].closeDetails();this.aSuccesses.splice(j,1);return}}};
sap.ui.commons.MessageBar.prototype.getSnapPoint=function(){if(!this.snapPoint){this.snapPoint=this.getAnchorSnapPoint();if(sap.ui.getCore().getConfiguration().getRTL()){this.snapPoint=this.snapPoint.replace("begin","right").replace("end","left")}else{this.snapPoint=this.snapPoint.replace("begin","left").replace("end","right")}}return this.snapPoint};
sap.ui.commons.MessageBar.prototype.open=function(){var a=0;var s=this.getSnapPoint();var b=null;var c=this.getAnchorID();if(c){b=jQuery.sap.domById(c)}if(!b){b=document.body}this.oPopup.open(a,s,s,b,"0 0");if(this.oDropPosition){this.oPopup._$().css('top',this.oDropPosition.top);if(s.indexOf("right")!=-1){this.oPopup._$().css('right',this.oDropPosition.right)}else{this.oPopup._$().css('left',this.oDropPosition.left)}}if(this.hasStyleClass("sapUiMsgBarOpen")){this.oList.setVisible(true)}};
sap.ui.commons.MessageBar.prototype.close=function(){if(this.oList&&this.oList.getVisible()){this.oList.setVisible(false)}var a=0;this.oPopup.close(a);this.maxToastsReached=false};
sap.ui.commons.MessageBar.prototype.updateCountersAndVisibility=function(){if(!this.getProperty("visible")){return}var i=this.getId();var c=jQuery.sap.domById(i+"__ErrorCount");if(!c){this.open();c=jQuery.sap.domById(i+"__ErrorCount")}var a=this.aErrors.length;var o=c.innerHTML;var n="("+a+")";var I=null;var C=null;if(n!=o){c.innerHTML=n;if(n=="(0)"){I=jQuery.sap.byId(i+"__ErrorImg");C=jQuery.sap.byId(i+"__ErrorCount");I.addClass("sapUiMsgBarZeroCount");C.addClass("sapUiMsgBarZeroCount")}else if(o=="(0)"){I=jQuery.sap.byId(i+"__ErrorImg");C=jQuery.sap.byId(i+"__ErrorCount");I.removeClass("sapUiMsgBarZeroCount");C.removeClass("sapUiMsgBarZeroCount")}}c=jQuery.sap.domById(i+"__WarningCount");a=this.aWarnings.length;o=c.innerHTML;n="("+a+")";I=null;C=null;if(n!=o){c.innerHTML=n;if(n=="(0)"){I=jQuery.sap.byId(i+"__WarningImg");C=jQuery.sap.byId(i+"__WarningCount");I.addClass("sapUiMsgBarZeroCount");C.addClass("sapUiMsgBarZeroCount")}else if(o=="(0)"){I=jQuery.sap.byId(i+"__WarningImg");C=jQuery.sap.byId(i+"__WarningCount");I.removeClass("sapUiMsgBarZeroCount");C.removeClass("sapUiMsgBarZeroCount")}}c=jQuery.sap.domById(i+"__SuccessCount");a=this.aSuccesses.length;o=c.innerHTML;n="("+a+")";I=null;C=null;if(n!=o){c.innerHTML=n;if(n=="(0)"){I=jQuery.sap.byId(i+"__SuccessImg");C=jQuery.sap.byId(i+"__SuccessCount");I.addClass("sapUiMsgBarZeroCount");C.addClass("sapUiMsgBarZeroCount")}else if(o=="(0)"){I=jQuery.sap.byId(i+"__SuccessImg");C=jQuery.sap.byId(i+"__SuccessCount");I.removeClass("sapUiMsgBarZeroCount");C.removeClass("sapUiMsgBarZeroCount")}}if(this.aErrors.length==0&&this.aWarnings.length==0&&this.aSuccesses.length==0){this.close();return}else{this.open()}if(this.oList&&this.oList.getVisible()){this.oList.setMessages(this.aSuccesses.concat(this.aWarnings).concat(this.aErrors))}this.checkForToast()};
sap.ui.commons.MessageBar.prototype.toggleList=function(){if(!this.oList){var l=this.getId()+"__List";this.oList=new sap.ui.commons.MessageList(l,{anchorId:this.getId(),maxListed:this.getMaxListed()})}var v=this.oList.getVisible();if(!v){this.oList.setMessages(this.aSuccesses.concat(this.aWarnings).concat(this.aErrors));this.addStyleClass("sapUiMsgBarOpen")}else{this.removeStyleClass("sapUiMsgBarOpen")}this.oList.setVisible(!v)};
sap.ui.commons.MessageBar.prototype.backHome=function(){var p=this.oPopup._$();if(this.oList&&this.oList.getVisible()){this.toggleList();var t=this;if(this.snapPoint.indexOf("right")!=-1){p.animate({right:this.oHomePosition.right+"px",top:this.oHomePosition.top+"px"},200,function(){t.toggleList()})}else{p.animate({left:this.oHomePosition.left+"px",top:this.oHomePosition.top+"px"},200,function(){t.toggleList()})}}else{if(this.snapPoint.indexOf("right")!=-1){p.animate({right:this.oHomePosition.right+"px",top:this.oHomePosition.top+"px"},200)}else{p.animate({left:this.oHomePosition.left+"px",top:this.oHomePosition.top+"px"},200)}}this.oDropPosition=null;this.removeStyleClass("sapUiMsgBarMoved")};
sap.ui.commons.MessageBar.prototype.addMessages=function(m){if(!m){return}for(var i=0,l=m.length;i<l;i++){this.deleteOneMessage(m[i].getId());switch(m[i].getType()){case sap.ui.commons.MessageType.Error:this.aErrors.push(m[i]);break;case sap.ui.commons.MessageType.Warning:this.aWarnings.push(m[i]);break;case sap.ui.commons.MessageType.Success:this.aSuccesses.push(m[i]);break;default:jQuery.sap.log.debug("ERROR: MessageBar supplied messageType="+m[i].getType())}}this.addToasts(m);this.updateCountersAndVisibility();return this};
sap.ui.commons.MessageBar.prototype.deleteMessages=function(I){if(!I){return}for(var i=0,l=I.length;i<l;i++){this.deleteOneMessage(I[i]);this.deleteToast(I[i])}this.updateCountersAndVisibility();return this};
sap.ui.commons.MessageBar.prototype.deleteAllMessages=function(){for(var j=this.aErrors.length-1;j>=0;j--){this.aErrors[j].closeDetails()}for(var j=this.aWarnings.length-1;j>=0;j--){this.aWarnings[j].closeDetails()}for(var j=this.aSuccesses.length-1;j>=0;j--){this.aSuccesses[j].closeDetails()}this.aErrors=[];this.aWarnings=[];this.aSuccesses=[];this.aToasts=[];this.updateCountersAndVisibility();return this};
sap.ui.commons.MessageBar.prototype.setVisible=function(v){this.setProperty("visible",v);if(v){this.updateCountersAndVisibility()}else{this.close()}return this};
