/*!
 * SAP UI development toolkit for HTML5 (SAPUI5/OpenUI5)
 * (c) Copyright 2009-2014 SAP AG or an SAP affiliate company. 
 * Licensed under the Apache License, Version 2.0 - see LICENSE.txt.
 */
jQuery.sap.declare("sap.ui.commons.RadioButton");jQuery.sap.require("sap.ui.commons.library");jQuery.sap.require("sap.ui.core.Control");sap.ui.core.Control.extend("sap.ui.commons.RadioButton",{metadata:{library:"sap.ui.commons",properties:{"text":{type:"string",group:"Data",defaultValue:null},"visible":{type:"boolean",group:"Appearance",defaultValue:true},"enabled":{type:"boolean",group:"Behavior",defaultValue:true},"editable":{type:"boolean",group:"Behavior",defaultValue:true},"selected":{type:"boolean",group:"Data",defaultValue:false},"valueState":{type:"sap.ui.core.ValueState",group:"Data",defaultValue:sap.ui.core.ValueState.None},"width":{type:"sap.ui.core.CSSSize",group:"Dimension",defaultValue:null},"textDirection":{type:"sap.ui.core.TextDirection",group:"Appearance",defaultValue:sap.ui.core.TextDirection.Inherit},"groupName":{type:"string",group:"Behavior",defaultValue:'sapUiRbDefaultGroup'},"key":{type:"string",group:"Data",defaultValue:null}},associations:{"ariaDescribedBy":{type:"sap.ui.core.Control",multiple:true,singularName:"ariaDescribedBy"},"ariaLabelledBy":{type:"sap.ui.core.Control",multiple:true,singularName:"ariaLabelledBy"}},events:{"select":{}}}});sap.ui.commons.RadioButton.M_EVENTS={'select':'select'};
sap.ui.commons.RadioButton.prototype.onclick=function(e){if(this.getEnabled()&&e.target.id==(this.getId()+"-RB")){this.focus()}if(!!sap.ui.Device.browser.internet_explorer&&(!this.getEnabled())){this.$().attr("tabindex",0).toggleClass("sapUiRbFoc")}this.userSelect(e)};
sap.ui.commons.RadioButton.prototype.onsapspace=function(e){if(this.getEnabled()&&e.target.id==(this.getId()+"-RB")){this.focus()}this.userSelect(e)};
sap.ui.commons.RadioButton.prototype.onsaptabnext=function(e){if(!!sap.ui.Device.browser.internet_explorer){this.bTabPressed=true;var t=this;window.setTimeout(function(){t.bTabPressed=false},100)}};
sap.ui.commons.RadioButton.prototype.onfocusin=function(e){if(this.getEnabled()&&e.target.id==(this.getId()+"-RB")){if(this.bTabPressed){var f=jQuery(":sapFocusable"),F=false;for(var i=0;i<f.length;i++){if(F&&f[i].parentNode!=e.target&&f[i].tabIndex!="-1"){f[i].focus();e.preventDefault();break}if(e.target==f[i]){F=true}}}else{this.focus()}}};
sap.ui.commons.RadioButton.prototype.onfocusout=function(e){if(!!sap.ui.Device.browser.internet_explorer&&(!this.getEnabled())){this.$().attr("tabindex",-1).toggleClass("sapUiRbFoc")}};
sap.ui.commons.RadioButton.prototype.userSelect=function(e){if(this.getEnabled()&&this.getEditable()){var s=this.getSelected();if(!s){this.setSelected(true);this.fireSelect({})}}else{e.preventDefault()}};
sap.ui.commons.RadioButton.prototype.setSelected=function(s){var S=this.getSelected();this.setProperty("selected",s,true);s=this.getSelected();if(s){if(this.getGroupName()&&(this.getGroupName()!="")){var o=document.getElementsByName(this.getGroupName());for(var i=0;i<o.length;i++){var a=o[i];if(a.id&&(a.id.length>3)&&(a.id.substr(a.id.length-3)=="-RB")){var c=sap.ui.getCore().getElementById(a.id.substr(0,a.id.length-3));if(c instanceof sap.ui.commons.RadioButton&&(c!=this)){c.setSelected(false)}}}}}if((S!=s)&&this.getDomRef()&&this.getRenderer().setSelected){this.getRenderer().setSelected(this,s)}return this};
sap.ui.commons.RadioButton.prototype.getTooltipDomRefs=function(){return this.$().children()};
