/*!
 * SAP UI development toolkit for HTML5 (SAPUI5/OpenUI5)
 * (c) Copyright 2009-2014 SAP AG or an SAP affiliate company. 
 * Licensed under the Apache License, Version 2.0 - see LICENSE.txt.
 */
jQuery.sap.declare("sap.m.ButtonRenderer");sap.m.ButtonRenderer={};
sap.m.ButtonRenderer.render=function(r,b){if(!b.getVisible()){return}var t=b.getType();var w=b.getWidth();var e=b.getEnabled();var E=false;r.write("<button type=\"button\"");r.writeControlData(b);if(t!==sap.m.ButtonType.Unstyled){r.addClass("sapMBtn")}if(sap.ui.Device.system.desktop){r.addClass("sapMBtnDesktop")}if(!b._isPlatformDependent){if(!b.getIcon()){if(t!=sap.m.ButtonType.Back&&t!=sap.m.ButtonType.Up){r.addClass("sapMBtnPaddingLeft")}if(b.getText()){r.addClass("sapMBtnPaddingRight")}}else{if(b.getIcon()&&b.getText()&&b.getIconFirst()){r.addClass("sapMBtnPaddingRight")}if(b.getIcon()&&b.getText()&&!b.getIconFirst()){r.addClass("sapMBtnPaddingLeft")}}}if(b._isPlatformDependent){if(!e){if(t==sap.m.ButtonType.Back||t==sap.m.ButtonType.Up){r.addClass("sapMBtn"+jQuery.sap.escapeHTML(t)+"Disabled")}else{if(t!=sap.m.ButtonType.Unstyled){r.addClass("sapMBtnDisabled")}}}else{if(t!=""&&t!=sap.m.ButtonType.Unstyled){r.addClass("sapMBtn"+jQuery.sap.escapeHTML(t))}}}else if(t!==sap.m.ButtonType.Unstyled){if(t!==""){r.addClass("sapMBtn"+jQuery.sap.escapeHTML(t))}if(!e){r.addClass("sapMBtnDisabled");r.writeAttribute("tabindex","-1")}else if(sap.ui.Device.system.desktop){r.writeAttribute("tabindex","0");r.addClass("sapMFocusable");switch(t){case sap.m.ButtonType.Accept:case sap.m.ButtonType.Reject:case sap.m.ButtonType.Emphasized:r.addClass("sapMBtnInverted")}}}if(b.getIcon()&&!b.getText()&&t!=sap.m.ButtonType.Back){if(!e){r.addClass("sapMBtnIconDisabled")}else{r.addClass("sapMBtnIcon")}}if(w!=""||w.toLowerCase()=="auto"){E=false;r.writeAttribute("style","width:"+w+";")}r.writeClasses();var T=b.getTooltip_AsString();if(T){r.writeAttributeEscaped("title",T)}r.write(">");if(this.renderButtonContentBefore){this.renderButtonContentBefore(r,b)}if(t===sap.m.ButtonType.Accept){E=true}if(t===sap.m.ButtonType.Reject){E=true}if(t===sap.m.ButtonType.Up){E=true}if(!b._isPlatformDependent&&t===sap.m.ButtonType.Back){E=true}if(b.getIcon()){E=true}if(E){r.write("<div");if(t!=sap.m.ButtonType.Unstyled){r.addClass("sapMBtnContent");if(b.getIcon()){r.addClass("sapMBtnContentWithIcon")}r.writeClasses()}r.write(">")}if(!b._isPlatformDependent){var B=sap.ui.core.IconPool.getIconURI("nav-back");this.writeInternalIconPoolHtml(r,b,t,sap.m.ButtonType.Back,B);this.writeInternalIconPoolHtml(r,b,t,sap.m.ButtonType.Up,B)}else{if(!sap.ui.Device.os.ios){var a=sap.ui.core.IconPool.getIconURI("accept");this.writeInternalIconPoolHtml(r,b,t,sap.m.ButtonType.Accept,a);var R=sap.ui.core.IconPool.getIconURI("decline");this.writeInternalIconPoolHtml(r,b,t,sap.m.ButtonType.Reject,R);var u=sap.ui.core.IconPool.getIconURI("navigation-left-arrow");this.writeInternalIconPoolHtml(r,b,t,sap.m.ButtonType.Up,u)}}if(b.getIcon()&&b.getIconFirst()){this.writeImgHtml(r,b)}this.writeTextHtml(r,b,E,t);if(b.getIcon()&&!b.getIconFirst()){this.writeImgHtml(r,b)}if(E){r.write("</div>")}if(this.renderButtonContentAfter){this.renderButtonContentAfter(r,b)}r.write("</button>")};
sap.m.ButtonRenderer.writeTextHtml=function(r,b,e,t){if(b.getText()){r.write("<span");if(!e&&t!==sap.m.ButtonType.Unstyled){r.addClass("sapMBtnContent");r.writeClasses()}if(b.getIcon()&&b.getText()){r.addClass("sapMBtnContentSpan");r.writeClasses()}r.write(">");r.writeEscaped(b.getText());r.write("</span>")}};
sap.m.ButtonRenderer.writeImgHtml=function(r,b){r.renderControl(b._getImage((b.getId()+"-img"),b.getIcon(),b.getActiveIcon(),b.getIconDensityAware()))};
sap.m.ButtonRenderer.writeInternalIconPoolHtml=function(r,b,t,c,u){if(t===c){if(b._imageBtn){b._imageBtn.setSrc(u)}else{r.renderControl(b._getInternalIconBtn((b.getId()+"-iconBtn"),u))}}};
