/*
 * @copyright
 */
jQuery.sap.declare("sap.m.ObjectHeaderRenderer");jQuery.sap.require("sap.ui.core.IconPool");sap.m.ObjectHeaderRenderer={};
sap.m.ObjectHeaderRenderer._isEmptyObject=function(o){if(!o){return true}if((!o._isEmpty||!o._isEmpty())&&(!o.getVisible||o.getVisible())){return false}return true};
sap.m.ObjectHeaderRenderer._isEmptyArray=function(a){if(a){for(var i=0;i<a.length;i++){if(!sap.m.ObjectHeaderRenderer._isEmptyObject(a[i])){return false}}}return true};
sap.m.ObjectHeaderRenderer._isEmptyRow=function(l,r){return sap.m.ObjectHeaderRenderer._isEmptyObject(l)&&sap.m.ObjectHeaderRenderer._isEmptyArray(r)};
sap.m.ObjectHeaderRenderer._renderObjects=function(r,o){for(var i=0;i<o.length;i++){if(o[i]instanceof sap.ui.core.Control){r.renderControl(o[i])}}};
sap.m.ObjectHeaderRenderer._getIcons=function(o){var i=[];if(o.getShowMarkers()){o._oFavIcon.setVisible(o.getMarkFavorite());o._oFlagIcon.setVisible(o.getMarkFlagged());i.push(o._oPlaceholderIcon);i.push(o._oFavIcon);i.push(o._oFlagIcon)}return i};
sap.m.ObjectHeaderRenderer.renderAttribute=function(r,o,a,f){r.write("<div");r.addClass("sapMOHAttr");r.writeClasses();if(f){r.addStyle("width","100%");r.writeStyles()}r.write(">");r.renderControl(a);r.write("</div>")};
sap.m.ObjectHeaderRenderer.renderRow=function(r,o,l,R){if(sap.m.ObjectHeaderRenderer._isEmptyRow(l,R)){return}r.write("<div");r.addClass("sapMOHAttrRow");r.writeClasses();r.write(">");if(!sap.m.ObjectHeaderRenderer._isEmptyObject(l)){this.renderAttribute(r,o,l,sap.m.ObjectHeaderRenderer._isEmptyArray(R))}else if(sap.m.ObjectHeaderRenderer._isEmptyObject(l)&&!sap.m.ObjectHeaderRenderer._isEmptyArray(R)){if(R[0]instanceof sap.m.ProgressIndicator){r.write("<div");r.addClass("sapMOHAttr");r.writeClasses();r.write(">");r.write("</div>")}}if(!sap.m.ObjectHeaderRenderer._isEmptyArray(R)){r.write("<div");if(R[0]instanceof sap.m.ProgressIndicator){r.addClass("sapMOHStatusFixedWidth")}else if(R[0]instanceof sap.ui.core.Icon){r.addClass("sapMOHStatusFixedWidth");r.addClass("sapMObjStatusMarker")}else{r.addClass("sapMOHStatus")}r.writeClasses();r.write(">");sap.m.ObjectHeaderRenderer._renderObjects(r,R);r.write("</div>")}r.write("</div>")};
sap.m.ObjectHeaderRenderer.renderAttributesAndStatuses=function(r,o){var a=o.getAttributes();var v=[];for(var i=0;i<a.length;i++){if(a[i].getVisible()){v.push(a[i])}}var A=v.length;var I=[];var b=sap.m.ObjectHeaderRenderer._getIcons(o);if(!sap.m.ObjectHeaderRenderer._isEmptyArray(b)){I.push(b)}if(o.getFirstStatus()){I.push([o.getFirstStatus()])}if(o.getSecondStatus()){I.push([o.getSecondStatus()])}if(o.getStatuses()){var s=o.getStatuses();for(var i=0;i<s.length;i++){if(!s[i].getVisible||s[i].getVisible()){if(s[i]instanceof sap.m.ObjectStatus||s[i]instanceof sap.m.ProgressIndicator){I.push([s[i]])}else{jQuery.sap.log.warning("Only sap.m.ObjectStatus or sap.m.ProgressIndicator are allowed in \"sap.m.ObjectHeader.statuses\" aggregation."+" Current object is "+s[i].constructor.getMetadata().getName()+" with id \""+s[i].getId()+"\"")}}}}var c=I.length;var n=A>c?A:c;for(var i=0;i<n;i++){this.renderRow(r,o,v[i],I[i])}};
sap.m.ObjectHeaderRenderer.renderNumber=function(r,o){if(o.getNumber()){r.write("<div");r.writeAttribute("id",o.getId()+"-numberdiv");r.addClass("sapMOHNumberDiv");r.writeClasses();r.write(">");r.write("<span");r.writeAttribute("id",o.getId()+"-number");r.addClass("sapMOHNumber");r.addClass("sapMOHNumberState"+o.getNumberState());r.writeClasses();r.write(">");r.writeEscaped(o.getNumber());r.write("</span>");if(o.getNumberUnit()){r.write("<span");r.writeAttribute("id",o.getId()+"-numberUnit");r.addClass("sapMOHNumberUnit");r.addClass("sapMOHNumberState"+o.getNumberState());r.writeClasses();r.write(">");r.writeEscaped(o.getNumberUnit());r.write("</span>")}r.write("</div>")}};
sap.m.ObjectHeaderRenderer.renderTitle=function(r,o){o._oTitleArrowIcon.setVisible(o.getShowTitleSelector());if(o.getShowTitleSelector()&&o._oTitleArrowIcon.getVisible()){r.write("<div");r.addClass("sapMOHTitleAndArrow");r.writeClasses();r.write(">")}if(o.getTitle()){o._titleText.setText(o.getTitle());r.write("<span");r.writeAttribute("id",o.getId()+"-title");r.addClass("sapMOHTitle");if(o.getTitleActive()){r.addClass("sapMOHTitleActive")}if(o.getShowTitleSelector()){r.addClass("sapMOHTitleFollowArrow")}r.writeClasses();r.write(">");o._titleText.addStyleClass("sapMOHTitle");r.renderControl(o._titleText);r.write("</span>")}if(o.getShowTitleSelector()){r.write("<span");r.addClass("sapMOHTitleArrow");r.writeClasses();r.write(">");r.renderControl(o._oTitleArrowIcon);r.write("</span>")}if(o.getShowTitleSelector()&&o._oTitleArrowIcon.getVisible()){r.write("</div>")}};
sap.m.ObjectHeaderRenderer.renderFullTitle=function(r,o){if(!o.getNumber()){r.addClass("sapMOHTitleDivFull")}};
sap.m.ObjectHeaderRenderer.renderFullOH=function(r,o){if(o.getIntro()){r.write("<div");r.addClass("sapMOHIntro");if(o.getIntroActive()){r.addClass("sapMOHIntroActive")}r.writeClasses();r.write(">");r.write("<span");r.writeAttribute("id",o.getId()+"-intro");r.write(">");r.writeEscaped(o.getIntro());r.write("</span>");r.write("</div>")}r.write("<div");r.addClass("sapMOHTopRow");r.writeClasses();r.write(">");r.write("<div");r.writeAttribute("id",o.getId()+"-titlediv");r.addClass("sapMOHTitleDiv");if(o._hasIcon()){r.addClass("sapMOHTitleIcon")}this.renderFullTitle(r,o);r.writeClasses();r.write(">");if(o._hasIcon()){r.write("<div");r.addClass("sapMOHIcon");if(o.getIconActive()){r.addClass("sapMPointer")}r.writeClasses();r.write(">");r.renderControl(o._getImageControl());r.write("</div>")}this.renderTitle(r,o);r.write("</div>");this.renderNumber(r,o);r.write("<div class=\"sapMOHDivider\"/>");r.write("</div>");if(o._hasBottomContent()){r.write("<div");r.addClass("sapMOHBottomRow");r.writeClasses();r.write(">");this.renderAttributesAndStatuses(r,o);r.write("<div class=\"sapMOHDivider\"/>");r.write("</div>")}};
sap.m.ObjectHeaderRenderer.renderCondensedOH=function(r,o){r.write("<div");r.writeAttribute("id",o.getId()+"-titlediv");r.addClass("sapMOHTitleDiv");this.renderFullTitle(r,o);r.writeClasses();r.write(">");this.renderTitle(r,o);r.write("</div>");this.renderNumber(r,o);var f=o.getAttributes()[0];if(f&&!f._isEmpty()){this.renderAttribute(r,o,f)}};
sap.m.ObjectHeaderRenderer.render=function(r,o){if(!o.getVisible()){return}var c=o.getCondensed();r.write("<div");r.writeControlData(o);r.addClass("sapMOH");if(c){r.addClass("sapMOHC");r.addClass("sapMOHBg"+o.getBackgroundDesign())}r.writeClasses();var t=o.getTooltip_AsString();if(t){r.writeAttributeEscaped("title",t)}r.write(">");if(c){this.renderCondensedOH(r,o)}else{this.renderFullOH(r,o)}r.write("<div class=\"sapMOHLastDivider\"/>");r.write("</div>")};
