/*!
 * SAP UI development toolkit for HTML5 (SAPUI5/OpenUI5)
 * (c) Copyright 2009-2014 SAP AG or an SAP affiliate company. 
 * Licensed under the Apache License, Version 2.0 - see LICENSE.txt.
 */
jQuery.sap.declare("sap.m.SearchFieldRenderer");sap.m.SearchFieldRenderer={};
sap.m.SearchFieldRenderer.render=function(r,s){if(!s.getVisible()){return}var a=r;var S=s.getShowMagnifier();var p=s.getPlaceholder();var v=s.getValue();var w=s.getProperty("width");a.write("<div");a.writeControlData(s);if(w){a.writeAttribute("style","width:"+w+";")}a.addClass("sapMSF");if(S){a.addClass("sapMSFM")}if(sap.ui.Device.os.android&&!(sap.ui.Device.browser.chrome)){if(sap.ui.Device.os.version<3){a.addClass("sapMSFA2")}else if(sap.ui.Device.os.version<=4){a.addClass("sapMSFA4")}}if(v){a.addClass("sapMSFVal")}if(!s.getEnabled()){a.addClass("sapMSFDisabled")}a.writeClasses();var t=s.getTooltip_AsString();if(t){a.writeAttributeEscaped("title",t)}a.write(">");if(s._sDesign){this.renderBcd(a,s,S,p,v)}else{this.renderMvi(a,s,S,p,v)}a.write("</div>")};
sap.m.SearchFieldRenderer.renderMvi=function(r,s,S,p,v){var i=s.getId();if(S){r.write('<div class="sapMSFMG"></div>')}r.write('<form method="post" action="javascript:void(0);">');if(!s._hasPlacehoder&&p){r.write("<label ");r.writeAttribute("id",i+"-P");r.writeAttribute("for",i+"-I");r.addClass("sapMSFPlaceholder");r.writeClasses();r.write(">");r.writeEscaped(p);r.write("</label>")}r.write('<input type="search" autocorrect="off"');r.writeAttribute("id",s.getId()+"-I");r.addClass("sapMSFI");if(sap.ui.Device.os.ios&&sap.ui.Device.os.version>5){r.addClass("sapMSFIIos6")}if(!s.getEnabled()){r.addClass("sapMSFIDisabled")}r.writeClasses();if(!s.getEnabled()){r.writeAttribute("disabled","disabled")}if(S){r.writeAttribute("results",0)}if(p){r.writeAttributeEscaped("placeholder",p)}if(s.getMaxLength()){r.writeAttribute("maxLength",s.getMaxLength())}if(v){r.writeAttributeEscaped("value",v)}r.write("></form>");if(s.getEnabled()){r.write("<div");r.writeAttribute("id",s.getId()+"-reset");r.addClass("sapMSFR");r.writeClasses();r.write("></div>")}};
sap.m.SearchFieldRenderer.renderBcd=function(r,s,S,p,v){var i=s.getId();r.write('<div');r.addClass('sapMSFB');if(s.getShowRefreshButton()&&!s.getValue()){r.addClass('sapMSFReload')}if(s._bNoFlex){r.addClass('sapMSFNoFlex')}r.writeClasses();r.write('>');r.write('<form method="post" action="javascript:void(0);">');if(!s._hasPlacehoder&&p){r.write("<label ");r.writeAttribute("id",i+"-P");r.writeAttribute("for",i+"-I");r.addClass("sapMSFPlaceholder");r.writeClasses();r.write(">");r.writeEscaped(p);r.write("</label>")}r.write('<input type="search" autocorrect="off"');r.writeAttribute("id",s.getId()+"-I");r.addClass("sapMSFI");if(sap.ui.Device.os.android&&sap.ui.Device.os.version>=4&&sap.ui.Device.os.version<4.1){r.addClass("sapMSFIA4")}if(!s.getEnabled()){r.addClass("sapMSFIDisabled")}r.writeClasses();if(!s.getEnabled()){r.writeAttribute("disabled","disabled")}if(p){r.writeAttributeEscaped("placeholder",p)}if(s.getMaxLength()){r.writeAttribute("maxLength",s.getMaxLength())}if(v){r.writeAttributeEscaped("value",v)}r.write(">");if(s.getEnabled()){r.write("<div");r.writeAttribute("id",s.getId()+"-reset");r.addClass("sapMSFR");r.writeClasses();r.write("></div>")}r.write("</form>");if(s._oButton){r.renderControl(s._oButton)}r.write("</div>")};
