/*!
 * SAP UI development toolkit for HTML5 (SAPUI5/OpenUI5)
 * (c) Copyright 2009-2014 SAP AG or an SAP affiliate company. 
 * Licensed under the Apache License, Version 2.0 - see LICENSE.txt.
 */
jQuery.sap.declare("sap.m.routing.RouteMatchedHandler");jQuery.sap.require("sap.ui.base.Object");jQuery.sap.require("sap.ui.core.routing.Router");jQuery.sap.require("sap.ui.core.routing.History");jQuery.sap.require("sap.m.InstanceManager");jQuery.sap.require("sap.m.SplitContainer");jQuery.sap.require("sap.m.NavContainer");sap.ui.base.Object.extend("sap.m.routing.RouteMatchedHandler",{constructor:function(r,c){this._aQueue=[];if(c===undefined){this._bCloseDialogs=true}else{this._bCloseDialogs=!!c}r.attachRouteMatched(this._onHandleRouteMatched,this);r.attachRoutePatternMatched(this._handleRoutePatternMatched,this);this._oRouter=r}});
sap.m.routing.RouteMatchedHandler.prototype.destroy=function(){this._oRouter.detachRouteMatched(this._onHandleRouteMatched,this);this._oRouter.detachRoutePatternMatched(this._handleRoutePatternMatched,this);this._oRouter=null;return this};
sap.m.routing.RouteMatchedHandler.prototype.setCloseDialogs=function(c){this._bCloseDialogs=!!c;return this};
sap.m.routing.RouteMatchedHandler.prototype.getCloseDialogs=function(){return this._bCloseDialogs};
sap.m.routing.RouteMatchedHandler.prototype._handleRoutePatternMatched=function(e){var t=+e.getParameter("config").viewLevel,h=sap.ui.core.routing.History.getInstance(),b,r=this._createResultingNavigations(e.getParameter("name"));this._closeDialogs();if(isNaN(t)||isNaN(this._iCurrentViewLevel)||t===this._iCurrentViewLevel){b=h.getDirection()==="Backwards"}else{b=t<this._iCurrentViewLevel}while(r.length){this._handleRouteMatched(r.shift().oParams,b)}this._iCurrentViewLevel=t};
sap.m.routing.RouteMatchedHandler.prototype._onHandleRouteMatched=function(e){this._aQueue.push({oTargetControl:e.getParameter("targetControl"),oArguments:e.getParameter("arguments"),oConfig:e.getParameter("config"),oView:e.getParameter("view"),sRouteName:e.getParameter("name")})};
sap.m.routing.RouteMatchedHandler.prototype._createResultingNavigations=function(r){var i,f,c,C,o,R=[],v,I,b,p,a;while(this._aQueue.length){f=false;c=this._aQueue.shift();C=c.oTargetControl;I=C instanceof sap.m.SplitContainer;b=C instanceof sap.m.NavContainer;v=c.oView;o={oContainer:C,oParams:c,bIsMasterPage:(I&&!!C.getMasterPage(v.getId()))};p=I&&c.oConfig.preservePageInSplitContainer&&C.getCurrentPage(o.bIsMasterPage)&&r!==c.sRouteName;if(!(b||I)||!v){continue}for(i=0;i<R.length;i++){a=R[i];if(a.oContainer!==C){continue}if(b||sap.ui.Device.system.phone){R.splice(i,1);R.push(o);f=true;break}if(a.bIsMasterPage===o.bIsMasterPage){if(p){break}R.splice(i,1);R.push(o);f=true;break}else{continue}}if(C instanceof sap.m.SplitContainer&&!sap.ui.Device.system.phone){o.bIsMasterPage=!!C.getMasterPage(v.getId())}if(!f){if(!!C.getCurrentPage(o.bIsMasterPage)&&p){continue}R.push(o)}}return R};
sap.m.routing.RouteMatchedHandler.prototype._handleRouteMatched=function(p,b){var t=p.oTargetControl,P,a=p.oArguments,T=p.oConfig.transition||"",o=p.oConfig.transitionParameters,v=p.oView.getId(),n=t instanceof sap.m.SplitContainer&&!!t.getMasterPage(v);if(t.getCurrentPage(n).getId()===v){jQuery.sap.log.info("navigation to view with id: "+v+" is skipped since it already is displayed by its targetControl");return}jQuery.sap.log.info("navigation to view with id: "+v+" the targetControl is "+t.getId()+" backwards is "+b);if(b){P=t.getPreviousPage(n);if(!P||P.getId()!==v){t.insertPreviousPage(v,T,a)}t.backToPage(v,a,o)}else{t.to(v,T,a,o)}};
sap.m.routing.RouteMatchedHandler.prototype._closeDialogs=function(){if(!this._bCloseDialogs){return}if(sap.m.InstanceManager.hasOpenPopover()){sap.m.InstanceManager.closeAllPopovers()}if(sap.m.InstanceManager.hasOpenDialog()){sap.m.InstanceManager.closeAllDialogs()}}
