/*!
 * SAP UI development toolkit for HTML5 (SAPUI5/OpenUI5)
 * (c) Copyright 2009-2014 SAP AG or an SAP affiliate company. 
 * Licensed under the Apache License, Version 2.0 - see LICENSE.txt.
 */
jQuery.sap.declare("sap.ui.demokit.CodeSampleContainer");jQuery.sap.require("sap.ui.demokit.library");jQuery.sap.require("sap.ui.core.Control");sap.ui.core.Control.extend("sap.ui.demokit.CodeSampleContainer",{metadata:{library:"sap.ui.demokit",properties:{"scriptElementId":{type:"string",group:"Misc",defaultValue:null},"uiAreaId":{type:"string",group:"Misc",defaultValue:null},"title":{type:"string",group:"Misc",defaultValue:null},"sourceVisible":{type:"boolean",group:"Misc",defaultValue:false},"width":{type:"sap.ui.core.CSSSize",group:"Misc",defaultValue:'90%'}},aggregations:{"_uiarea":{type:"sap.ui.demokit.UIAreaSubstitute",multiple:false,visibility:"hidden"}},events:{"apply":{}}}});sap.ui.demokit.CodeSampleContainer.M_EVENTS={'apply':'apply'};jQuery.sap.require("sap.ui.core.ResizeHandler");
sap.ui.demokit.CodeSampleContainer.prototype.init=function(){this._oUIArea=new sap.ui.demokit.UIAreaSubstitute(this.getUiAreaId());this.setAggregation("_uiarea",this._oUIArea);this._oCodeViewer=new sap.ui.demokit.CodeViewer({visible:false,source:"",press:[this._setCodeEditable,this],save:[this._saveAndApplyCode,this]});this._oCodeViewer.setParent(this);this._oShowCodeLink=new sap.ui.commons.Link({text:"Show Source",press:[this._toggleCodeDisplay,this]});this._oShowCodeLink.setParent(this);this._oApplyCodeLink=new sap.ui.commons.Link({visible:false,text:'Apply',press:[this._saveAndApplyCode,this]});this._oApplyCodeLink.setParent(this)};
sap.ui.demokit.CodeSampleContainer.prototype.setSourceVisible=function(s){this.setProperty("sourceVisible",s);this._oCodeViewer&&this._oCodeViewer.setVisible(this.getSourceVisible());this._oShowCodeLink&&this._oShowCodeLink.setText(this.getSourceVisible()?"Hide Source":"Show Source");this._oApplyCodeLink&&this._oApplyCodeLink.setVisible(this.getSourceVisible())};
sap.ui.demokit.CodeSampleContainer.prototype.setUiAreaId=function(I){this.setProperty("uiAreaId",I);var c;if(this._oUIArea){c=this._oUIArea.removeAllContent();this._oUIArea.destroy()}this._oUIArea=new sap.ui.demokit.UIAreaSubstitute(this.getUiAreaId());this.setAggregation("_uiarea",this._oUIArea);if(c){for(var i=0;i<c.length;i++){this._oUIArea.addContent(c[i])}}};
sap.ui.demokit.CodeSampleContainer.prototype.setScriptElementId=function(i){this.setProperty("scriptElementId",i);this._oCodeViewer.setSource(this._getSource());if(i&&!this._oScriptRef){var t=this;sap.ui.getCore().attachInitEvent(function(){t._oCodeViewer.setSource(t._getSource())})}};
sap.ui.demokit.CodeSampleContainer.prototype._getSource=function(){var s="!source not found! ("+this.getScriptElementId()+")";if(this.getScriptElementId()){this._oScriptRef=jQuery.sap.domById(this.getScriptElementId());if(this._oScriptRef){s=this._oScriptRef.innerHTML}}return s};
sap.ui.demokit.CodeSampleContainer.prototype._setCodeEditable=function(){this._oCodeViewer.setEditable(true);var t=this;setTimeout(function(){t._oCodeViewer.focus()},50)};
sap.ui.demokit.CodeSampleContainer.prototype._toggleCodeDisplay=function(){this.setSourceVisible(!this.getSourceVisible())};
sap.ui.demokit.CodeSampleContainer.prototype._saveAndApplyCode=function(){var sCode=this._oCodeViewer.getSource();if(this._oCodeViewer.getEditable()){sCode=this._oCodeViewer.getCurrentSource();this._oCodeViewer.setSource(sCode);this._oCodeViewer.setEditable(false)}this._oUIArea.destroyContent();if(!this.hasListeners("apply")){eval(sCode)}else{this.fireApply({code:sCode})}};
