/*!
 * SAP UI development toolkit for HTML5 (SAPUI5/OpenUI5)
 * (c) Copyright 2009-2014 SAP AG or an SAP affiliate company. 
 * Licensed under the Apache License, Version 2.0 - see LICENSE.txt.
 */
jQuery.sap.declare("sap.ui.demokit.UI5EntityCueCard");jQuery.sap.require("sap.ui.demokit.library");jQuery.sap.require("sap.ui.core.Control");sap.ui.core.Control.extend("sap.ui.demokit.UI5EntityCueCard",{metadata:{library:"sap.ui.demokit",properties:{"collapsible":{type:"boolean",group:"Misc",defaultValue:true},"expanded":{type:"boolean",group:"Misc",defaultValue:false},"navigable":{type:"boolean",group:"Misc",defaultValue:false},"entityName":{type:"string",group:"Misc",defaultValue:null},"style":{type:"sap.ui.demokit.UI5EntityCueCardStyle",group:"Misc",defaultValue:null}},events:{"navigate":{allowPreventDefault:true}}}});sap.ui.demokit.UI5EntityCueCard.M_EVENTS={'navigate':'navigate'};jQuery.sap.require("sap.ui.commons.Link");
sap.ui.demokit.UI5EntityCueCard.prototype.init=function(){this._oShowCueCardLink=new sap.ui.commons.Link({text:"Show All Settings",press:[this._toggleExpanded,this]});this._oShowCueCardLink.setParent(this);this._aHistory=[];this._iHistory=-1};
sap.ui.demokit.UI5EntityCueCard.prototype.setEntityName=function(e){if(e!==this.getEntityName()){this.setProperty("entityName",e);this._aHistory[++this._iHistory]=e;this._aHistory.length=this._iHistory+1}};
sap.ui.demokit.UI5EntityCueCard.prototype.back=function(){if(this._iHistory>0){this.setProperty("entityName",this._aHistory[--this._iHistory])}};
sap.ui.demokit.UI5EntityCueCard.prototype.forward=function(){if(this._iHistory+1<this._aHistory.length){this.setProperty("entityName",this._aHistory[++this._iHistory])}};
sap.ui.demokit.UI5EntityCueCard.prototype.setExpanded=function(e){this.setProperty("expanded",e);this._oShowCueCardLink&&this._oShowCueCardLink.setText(this.getExpanded()?"Hide Settings":"Show All Settings")};
sap.ui.demokit.UI5EntityCueCard.prototype.onclick=function(e){if(this.getNavigable()){var E=jQuery(e.target).attr("data-sap-ui-entity");if(E&&this.fireNavigate({entityName:E})){this.setEntityName(E)}}};
sap.ui.demokit.UI5EntityCueCard.prototype._toggleExpanded=function(){this.setExpanded(!this.getExpanded())};
sap.ui.demokit.UI5EntityCueCard.prototype._getDoc=function(){var E=this._oDocumentation;if(!E||E.name!==this.getEntityName()){E=undefined;l(this.getEntityName(),".control");if(!E){l(this.getEntityName(),".type")}this._oDocumentation=E}return E;function l(N,t){var P={".control":p,".type":a};var C="boolean int float number function object string void any Element Control Component";function p($){E=E||{doc:undefined,deprecation:undefined,properties:{},aggregations:{},associations:{},events:{},methods:{}};E.doc=E.doc||d($);E.deprecation=E.deprecation||c($);b($,"properties/property",function(e){E.properties[e.attr("name")]={kind:0,type:r(e.attr("type")||"string"),defaultValue:e.attr("defaultValue")||"empty/undefined",doc:d(e),deprecation:c(e)}});E.defaultAggregation=E.defaultAggregation||$.children("aggregations").attr("default");b($,"aggregations/aggregation",function(e){E.aggregations[e.attr("name")]={kind:e.attr("cardinality")==="0..1"?1:2,type:r(e.attr("type")||"sap.ui.core/Control"),cardinality:e.attr("cardinality")||"0..n",doc:d(e),deprecation:c(e)}});b($,"associations/association",function(e){E.associations[e.attr("name")]={kind:e.attr("cardinality")==="0..n"?4:3,type:r(e.attr("type")||"sap.ui.core/Control"),cardinality:e.attr("cardinality")||"0..1",doc:d(e),deprecation:c(e)}});b($,"events/event",function(e){var N=e.attr("name");E.events[N]={kind:5,doc:d(e),deprecation:c(e),parameters:[]};b(e,"parameters/parameter",function(f){E.events[N].parameters[f.attr("name")]={kind:6,type:r(f.attr("type")||"string"),doc:d(f),deprecation:c(f)}})});b($,"methods/method",function(e){var N=e.attr("name");E.methods[N]={kind:7,type:r(e.attr("type")||"sap.ui.core/void"),doc:d(e),deprecation:c(e),parameters:[]};b(e,"parameters/parameter",function(f){E.methods[N].parameters.push({kind:8,name:f.attr("name"),type:r(f.attr("type")||"sap.ui.core/Control"),doc:d(f),deprecation:c(f)})})});var B=$.children("baseType").text();if(B){l(B,".control")}}function a($){E=E||{doc:undefined,deprecation:false,values:{}};E.doc=E.doc||d($);E.deprecation=E.deprecation||c($);b($,"enumeration/value",function(e){var N=e.attr("name");E.values[N]={value:e.attr("value")||N,doc:d(e),deprecation:c(e)}});E.pattern=$.children("pattern").text();var B=$.children("baseType").text();if(B){l(B,".type")}}function b($,s,f){jQuery.each(s.split("/"),function(i,n){$=$.children(n)});$.each(function(i,e){f(jQuery(e))})}function d($){return $.children("documentation").text()}function c($){return $.children("deprecation").text()}function r(t){if(t.indexOf("/")>=0){return t.replace(/\//g,".")}else if(t&&t.indexOf(".")<0&&C.indexOf(t)>=0){return"sap.ui.core."+t}else{return N.split(".").slice(0,-1).concat([t.replace(/\//g,".")]).join(".")}}jQuery.ajax({async:false,url:jQuery.sap.getModulePath(N,t),dataType:'xml',success:function(x){P[t](jQuery(x.documentElement));E.name=N;E.metatype=t}})}};
sap.ui.demokit.UI5EntityCueCard.createDialog=function(){jQuery.sap.require("sap.ui.commons.Button");jQuery.sap.require("sap.ui.commons.Dialog");jQuery.sap.require("sap.ui.commons.Toolbar");var c=new sap.ui.demokit.UI5EntityCueCard({collapsible:false,expanded:true,navigable:true});var d=new sap.ui.commons.Dialog({title:"Cue Card",minWidth:"200px",minHeight:"200px",maxWidth:"75%",maxHeight:"75%",content:[new sap.ui.commons.Toolbar({standalone:false,items:[new sap.ui.commons.Button({text:"Back",press:function(){c.back()}}),new sap.ui.commons.Button({text:"Fwd",press:function(){c.forward()}})]}),c]});d.openForClass=function(C){c.setEntityName(C);this.rerender();this.open()};return d};
sap.ui.demokit.UI5EntityCueCard.attachToContextMenu=function(n){var d;jQuery(n||window.document).bind("contextmenu.sapDkCueCd",function(e){if(e.shiftKey&&e.ctrlKey){var c=jQuery(e.target).control(0);if(c&&(!d||!d.getDomRef()||(d.getDomRef()!==e.target&&!jQuery.contains(d.getDomRef(),e.target)))){d=d||sap.ui.demokit.UI5EntityCueCard.createDialog();d.openForClass(c.getMetadata().getName());e.preventDefault();e.stopPropagation()}}})};
sap.ui.demokit.UI5EntityCueCard.detachFromContextMenu=function(n){jQuery(n||window.document).unbind("contextmenu.sapDkCueCd")};
